package redestelecom;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;



public class Tramo extends javax.swing.JFrame {
    private Connection BaseDeDatos;
    private String []DatosEquipo = new String[5];
    private String []Fibras = new String[10]; 
    private String []RX = new String[10];
    private String []TX = new String[15];

 
    public Tramo(Connection conexionActiva) throws SQLException {
        initComponents();
        BaseDeDatos = conexionActiva;
        this.setLocationRelativeTo(null);
        setResizable(false);
        setTitle(".:: Generar tramo ::.");
        bloquearComboBoxes();
       
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxOrigen = new javax.swing.JComboBox<>();
        jComboBoxDestino = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBoxWL = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jComboBoxFOExt = new javax.swing.JComboBox<>();
        jComboBoxFOInt = new javax.swing.JComboBox<>();
        jComboBoxTXOpt = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jComboBoxConectores = new javax.swing.JComboBox<>();
        jComboBoxEmpalmes = new javax.swing.JComboBox<>();
        jComboBoxAmplificadores = new javax.swing.JComboBox<>();
        jComboBoxAtenuadores = new javax.swing.JComboBox<>();
        jComboBoxReceptores = new javax.swing.JComboBox<>();
        jComboBoxPzasConectores = new javax.swing.JComboBox<>();
        jComboBoxPzasEmpalmes = new javax.swing.JComboBox<>();
        jComboBoxPzasReceptores = new javax.swing.JComboBox<>();
        jComboBoxPzasAmplificadores = new javax.swing.JComboBox<>();
        jComboBoxPzasAtenuadores = new javax.swing.JComboBox<>();
        jButtonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Generar tramo");

        jComboBoxOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Origen", "La Paz, Baja California Sur" }));

        jComboBoxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Destino", "Cd. Constitución, Baja California Sur" }));

        jComboBoxWL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Longitud de onda", "1310", "1550", " " }));
        jComboBoxWL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxWLActionPerformed(evt);
            }
        });

        jComboBoxFOExt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFOExtActionPerformed(evt);
            }
        });

        jComboBoxFOInt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fibra óptica interna", " " }));
        jComboBoxFOInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFOIntActionPerformed(evt);
            }
        });

        jComboBoxTXOpt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transmisor óptico" }));

        jComboBoxConectores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conectores" }));
        jComboBoxConectores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxConectoresActionPerformed(evt);
            }
        });

        jComboBoxEmpalmes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empalmes" }));

        jComboBoxAmplificadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amplificadores" }));

        jComboBoxAtenuadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atenuadores" }));

        jComboBoxReceptores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Receptores" }));
        jComboBoxReceptores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxReceptoresActionPerformed(evt);
            }
        });

        jComboBoxPzasConectores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Piezas", "1", "2", "3", "4", "5" }));
        jComboBoxPzasConectores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPzasConectoresActionPerformed(evt);
            }
        });

        jComboBoxPzasEmpalmes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Piezas", "1", "2", "3", "4", "5" }));

        jComboBoxPzasReceptores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Piezas", "1", "2", "3", "4", "5" }));

        jComboBoxPzasAmplificadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Piezas", "1", "2", "3", "4", "5" }));

        jComboBoxPzasAtenuadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Piezas", "1", "2", "3", "4", "5" }));

        jButtonOK.setText("Cotizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jComboBoxFOExt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxFOInt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxTXOpt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxConectores, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxPzasConectores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxEmpalmes, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxPzasEmpalmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxReceptores, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxPzasReceptores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxAmplificadores, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxPzasAmplificadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxAtenuadores, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxPzasAtenuadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jComboBoxOrigen, 0, 260, Short.MAX_VALUE)
                            .addComponent(jComboBoxDestino, 0, 0, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jComboBoxWL, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxWL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxFOExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxFOInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTXOpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxConectores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPzasConectores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEmpalmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPzasEmpalmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAmplificadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPzasAmplificadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAtenuadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPzasAtenuadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxReceptores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPzasReceptores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxWLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxWLActionPerformed
        // TODO add your handling code here:
        String seleccion = jComboBoxWL.getSelectedItem().toString();
        if (seleccion != "Longitud de onda") {
            System.out.println(seleccion);
            desbloquearComboBoxes();
            int longOnda = Integer.parseInt(seleccion);
            try {
                loadRX(longOnda);
                loadTX(longOnda);
                loadFO(longOnda, "exterior");
                loadFO(longOnda, "interior");
            } catch (SQLException ex) {
                Logger.getLogger(Tramo.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.out.println("Elige un valor válido");
            bloquearComboBoxes();
        }
    }//GEN-LAST:event_jComboBoxWLActionPerformed

    private void jComboBoxFOExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFOExtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFOExtActionPerformed

    private void jComboBoxPzasConectoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPzasConectoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPzasConectoresActionPerformed

    private void jComboBoxConectoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxConectoresActionPerformed
        
    }//GEN-LAST:event_jComboBoxConectoresActionPerformed

    private void jComboBoxReceptoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxReceptoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxReceptoresActionPerformed

    private void jComboBoxFOIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFOIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFOIntActionPerformed

       private void loadRX (int WL) throws SQLException {
    String instruccion;
    Statement consulta;
    ResultSet rs;
    consulta = BaseDeDatos.createStatement();
     jComboBoxReceptores.removeAllItems();
 
     instruccion =  "select * from rx  where WL =" + Integer.toString(WL); //ORDER by 
     //instruccion = "Select * from rx order by price";
     rs= consulta.executeQuery(instruccion);
     int i = 0;
     while (rs.next()){
     RX[i]= rs.getString("Nombre");
     System.out.println("Receptores " + RX[i] );
     i++;
             jComboBoxReceptores.addItem(rs.getString("Nombre"));
     }
    }
       
           private void loadTX (int WL) throws SQLException {
    String instruccion;
    Statement consulta;
    ResultSet rs;
    consulta = BaseDeDatos.createStatement();
     jComboBoxTXOpt.removeAllItems();
 
     instruccion =  "select * from txoptic  where WL =" + Integer.toString(WL); //ORDER by 
     //instruccion = "Select * from rx order by price";
     rs= consulta.executeQuery(instruccion);
     int i = 0;
     while (rs.next()){
     TX[i]= rs.getString("Nombre");
     System.out.println("Transmisores " + TX[i] );
     i++;
             jComboBoxTXOpt.addItem(rs.getString("Nombre"));
     }
    }
    
    private void loadFO(int WL, String modo) throws SQLException {
        String instruccion;
        String instruccion2;
        Statement consulta;
        Statement consulta1;
        ResultSet respuesta;
        ResultSet res;
        consulta = BaseDeDatos.createStatement();
        consulta1= BaseDeDatos.createStatement();
        jComboBoxFOExt.removeAllItems();
        jComboBoxFOInt.removeAllItems();
        instruccion = "select * from producto where WL=" + Integer.toString(WL) + " and " + modo + " = true order by costo";//Fibras Exterior 
        instruccion2 = "select * from producto where WL=" + Integer.toString(WL) + " and " + modo + " = false order by costo";
        respuesta = consulta.executeQuery(instruccion);
        res = consulta1.executeQuery(instruccion2);
        //Fibras interiores
        int i = 0;
        while(respuesta.next()){
            Fibras[i] = respuesta.getString("Fabricante") + " " + respuesta.getString("Tipo") + ".";
            System.out.println("Fibra: " + Fibras[i]);
            i++;
            jComboBoxFOExt.addItem(respuesta.getString("Fabricante"));          
        } 
       respuesta.close();

        int j = 0;
        while (res.next()){
           Fibras[j] = res.getString("Fabricante") + " " + res.getString("Tipo") + ".";
           System.out.println("Fibra: " + Fibras[i]);
           j++;
           jComboBoxFOInt.addItem(res.getString("Fabricante"));
        }
    }
     
 
    
    private void colocarFOExterna() {
    }
    
    private void colocarFOInterna() {
        //
    }
    
    private void bloquearComboBoxes() {
        jComboBoxFOExt.setEnabled(false);
        jComboBoxFOInt.setEnabled(false);
        jComboBoxTXOpt.setEnabled(false);
        
        jComboBoxConectores.setEnabled(false);
        jComboBoxPzasConectores.setEnabled(false);
        jComboBoxEmpalmes.setEnabled(false);
        jComboBoxPzasEmpalmes.setEnabled(false);
        jComboBoxAmplificadores.setEnabled(false);
        jComboBoxPzasAmplificadores.setEnabled(false);
        jComboBoxAtenuadores.setEnabled(false);
        jComboBoxPzasAtenuadores.setEnabled(false);
        jComboBoxReceptores.setEnabled(false);
        jComboBoxPzasReceptores.setEnabled(false);
    }
    
    private void desbloquearComboBoxes() {
        jComboBoxFOExt.setEnabled(true);
        jComboBoxFOInt.setEnabled(true);
        jComboBoxTXOpt.setEnabled(true);
        
        jComboBoxConectores.setEnabled(true);
        jComboBoxPzasConectores.setEnabled(true);
        jComboBoxEmpalmes.setEnabled(true);
        jComboBoxPzasEmpalmes.setEnabled(true);
        jComboBoxAmplificadores.setEnabled(true);
        jComboBoxPzasAmplificadores.setEnabled(true);
        jComboBoxAtenuadores.setEnabled(true);
        jComboBoxPzasAtenuadores.setEnabled(true);
        jComboBoxReceptores.setEnabled(true);
        jComboBoxPzasReceptores.setEnabled(true);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tramo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tramo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tramo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tramo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConexionSQL BaseSQL = new ConexionSQL();
                Connection BD = BaseSQL.getConexionSQL();
                try {
                    new Tramo(BD).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Tramo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOK;
    private javax.swing.JComboBox<String> jComboBoxAmplificadores;
    private javax.swing.JComboBox<String> jComboBoxAtenuadores;
    private javax.swing.JComboBox<String> jComboBoxConectores;
    private javax.swing.JComboBox<String> jComboBoxDestino;
    private javax.swing.JComboBox<String> jComboBoxEmpalmes;
    private javax.swing.JComboBox<String> jComboBoxFOExt;
    private javax.swing.JComboBox<String> jComboBoxFOInt;
    private javax.swing.JComboBox<String> jComboBoxOrigen;
    private javax.swing.JComboBox<String> jComboBoxPzasAmplificadores;
    private javax.swing.JComboBox<String> jComboBoxPzasAtenuadores;
    private javax.swing.JComboBox<String> jComboBoxPzasConectores;
    private javax.swing.JComboBox<String> jComboBoxPzasEmpalmes;
    private javax.swing.JComboBox<String> jComboBoxPzasReceptores;
    private javax.swing.JComboBox<String> jComboBoxReceptores;
    private javax.swing.JComboBox<String> jComboBoxTXOpt;
    private javax.swing.JComboBox<String> jComboBoxWL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
